//
//  ContentView.swift
//  App (Generated by SwiftyLaunch 2.0)
//  https://docs.swiftylaun.ch/module/app
//

import InAppPurchaseKit
import NotifKit
import SharedKit
import SupabaseKit
import SwiftUI

struct ContentView: View {

	init() {

	}

	var body: some View {
		TabView {
			// Home Tab
			HomeView()
				.tabItem { Label("Home", systemImage: "house") }
			
			// Library Tab
			LibraryView()
				.tabItem { Label("Library", systemImage: "bookmark") }
			
			// Rewards Tab
			RewardsView()
				.tabItem { Label("Rewards", systemImage: "gift") }
			
			// Profile Tab
			ProfileView()
				.tabItem { Label("Profile", systemImage: "person") }

			#if DEBUG
				// Use this to create quick settings and toggles to streamline the development process.
				DeveloperSettingsView()
					.tabItem { Label("Developer", systemImage: "hammer") }
			#endif
		}
	}
}

#Preview {
	ContentView()
		.environmentObject(InAppPurchases())
}
