//
//  captureTaps.swift
//  AnalyticsKit (Generated by SwiftyLaunch 2.0)
//  https://docs.swiftylaun.ch/module/analyticskit/capture-taps
//

import SharedKit
import SwiftUI
import UIKit
import Mixpanel

/// A view modifier that captures button taps.
public struct CaptureTaps: ViewModifier {
	let buttonName: String
	let screenName: String?
	
	public init(buttonName: String, screenName: String? = nil) {
		self.buttonName = buttonName
		self.screenName = screenName
	}
	
	public func body(content: Content) -> some View {
		content
			.onTapGesture {
				var properties: [String: Any] = ["button_name": buttonName]
				if let screenName = screenName {
					properties["screen_name"] = screenName
				}
				Mixpanel.mainInstance().track(event: "button_tap", properties: properties)
			}
	}
}

/// This modifier will notify Mixpanel when a view is tapped
public extension View {
	func captureTaps(buttonName: String, screenName: String? = nil) -> some View {
		modifier(CaptureTaps(buttonName: buttonName, screenName: screenName))
	}
}
