//
//  captureViewActivity.swift
//  AnalyticsKit (Generated by SwiftyLaunch 2.0)
//  https://docs.swiftylaun.ch/module/analyticskit/capture-view-activity
//

import SwiftUI
import SharedKit
import Mixpanel

/// A view modifier that captures screen views.
public struct CaptureViewActivity: ViewModifier {
	let screenName: String

	public init(_ screenName: String) {
		self.screenName = screenName
	}

	public func body(content: Content) -> some View {
		content
			.onAppear {
				Mixpanel.mainInstance().track(event: "screen_view", properties: ["screen_name": screenName])
			}
	}
}

/// This modifier will notify Mixpanel when a View is active
public extension View {
	func captureViewActivity(_ screenName: String) -> some View {
		modifier(CaptureViewActivity(screenName))
	}
}
