//
//  ContentView.swift
//  App (Generated by SwiftyLaunch 2.0)
//  https://docs.swiftylaun.ch/module/app
//

import InAppPurchaseKit
import NotifKit
import SharedKit
import SupabaseKit
import SwiftUI

struct ContentView: View {

	init() {

	}

	var body: some View {
		TabView {

			// Example view on how to access the Database.
			DatabaseExampleView()
				.tabItem { Label("DB Exmpls.", systemImage: "externaldrive.badge.icloud") }

			// Pre-made Settings View for easy native-looking settings screen.
			SettingsView()
				.tabItem { Label("Settings", systemImage: "gear") }

			#if DEBUG

				// Use this to create quick settings and toggles to streamline the development process.
				DeveloperSettingsView()
					.tabItem { Label("Developer", systemImage: "hammer") }

			#endif
		}
	}
}

#Preview {
	ContentView()
		.environmentObject(InAppPurchases())
}
